DROP TABLE card CASCADE CONSTRAINTS;
DROP TABLE player CASCADE CONSTRAINTS;
DROP TABLE player_cards CASCADE CONSTRAINTS;
DROP TABLE game_state CASCADE CONSTRAINTS;
DROP TABLE field_cards CASCADE CONSTRAINTS;
DROP TABLE deck_cards CASCADE CONSTRAINTS;
DROP TABLE score_log CASCADE CONSTRAINTS;




-- 카드 테이블
CREATE TABLE card (
    id NUMBER PRIMARY KEY,
    month NUMBER(2) NOT NULL, -- 카드의 월 (1 ~ 12)
    type VARCHAR2(10) NOT NULL, -- 카드 타입 (광, 띠, 피, 쌍피 등)
    point NUMBER(5, 2) DEFAULT 0, -- 카드 점수
    is_special CHAR(1) DEFAULT 'N' CHECK (is_special IN ('Y', 'N')) -- 특수 카드 여부
);

comment on column card.id is '카드고유ID';
comment on column card.month is '카드의 월';
comment on column card.type is '카드 타입';
comment on column card.point is '카드 점수';
comment on column card.is_special is '특수카드여부';


-- 사용자 테이블
CREATE TABLE player (
    id NUMBER PRIMARY KEY,
    name VARCHAR2(50) NOT NULL, -- 플레이어 이름
    score NUMBER DEFAULT 0, -- 플레이어 점수
    is_turn CHAR(1) DEFAULT 'N' CHECK (is_turn IN ('Y', 'N')) -- 현재 턴 여부
);

comment on column player.id is '사용자고유ID';
comment on column player.name is '사용자이름';
comment on column player.score is '사용자점수';
comment on column player.is_turn is '현재 턴 여부';


-- 사용자 카드 테이블
CREATE TABLE player_cards (
    id NUMBER PRIMARY KEY,
    player_id NUMBER NOT NULL, -- 플레이어 ID
    card_id NUMBER NOT NULL, -- 카드 ID
    type VARCHAR2(10) NOT NULL, -- 카드 유형 ('HAND' or 'COLLECTED')
    CONSTRAINT fk_player FOREIGN KEY (player_id) REFERENCES player(id),
    CONSTRAINT fk_card FOREIGN KEY (card_id) REFERENCES card(id)
);

comment on column player_cards.id is '사용자 카드 고유 ID';
comment on column player_cards.player_id is '사용자 고유 ID';
comment on column player_cards.card_id is '카드 고유 ID';
comment on column player_cards.type is '카드 유형';


-- 게임 진행상태 테이블
CREATE TABLE game_state (
    id NUMBER PRIMARY KEY,
    turn_order NUMBER(1) DEFAULT 1, -- 현재 턴 순서 (1: 사용자, 2: AI)
    is_finished CHAR(1) DEFAULT 'N' CHECK (is_finished IN ('Y', 'N')) -- 게임 종료 여부
);

comment on column game_state.id is '게임 진행상태 고유 ID';
comment on column game_state.turn_order is '현재 턴 순서';
comment on column game_state.is_finished is '게임 종료 여부';


-- 장판 카드 테이블
CREATE TABLE field_cards (
    id NUMBER PRIMARY KEY,
    game_id NUMBER NOT NULL, -- 게임 ID
    card_id NUMBER NOT NULL, -- 카드 ID
    CONSTRAINT fk_game FOREIGN KEY (game_id) REFERENCES game_state(id),
    CONSTRAINT fk_card_field FOREIGN KEY (card_id) REFERENCES card(id)
);

comment on column field_cards.id is '장판 카드 고유 ID';
comment on column field_cards.game_id is '게임 ID';
comment on column field_cards.card_id is '카드 ID';


-- 덱 카드 테이블
CREATE TABLE deck_cards (
    id NUMBER PRIMARY KEY,
    game_id NUMBER NOT NULL, -- 게임 ID
    card_id NUMBER NOT NULL, -- 카드 ID
    CONSTRAINT fk_game_deck FOREIGN KEY (game_id) REFERENCES game_state(id),
    CONSTRAINT fk_card_deck FOREIGN KEY (card_id) REFERENCES card(id)
);

comment on column deck_cards.id is '덱 카드 고유 ID';
comment on column deck_cards.game_id is '게임 ID';
comment on column deck_cards.card_id is '카드 ID';


-- 점수기록 테이블
CREATE TABLE score_log (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id NUMBER NOT NULL, -- 게임 ID
    player_id NUMBER NOT NULL, -- 플레이어 ID
    action VARCHAR2(50) NOT NULL, -- 행동 ('카드 낸다', '점수 추가' 등)
    score_change NUMBER DEFAULT 0, -- 점수 변화량
    log_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP, -- 로그 시간
    CONSTRAINT fk_game_log FOREIGN KEY (game_id) REFERENCES game_state(id),
    CONSTRAINT fk_player_log FOREIGN KEY (player_id) REFERENCES player(id)
);

comment on column score_log.id is '점수 기록 고유 ID';
comment on column score_log.game_id is '게임 고유 ID';
comment on column score_log.player_id is '사용자 고유 ID';
comment on column score_log.action is '행동';
comment on column score_log.score_change is '점수 변화량';
comment on column score_log.log_time is '로그 시간';





